import sys
import time
import json
import requests
from database import query
from notifier import send_expo_notifications

EXPO_RECEIPTS_URL = "https://exp.host/--/api/v2/push/getReceipts"

def test_push():
    # 1. Fetch latest token
    rows = query("SELECT token, platform, user_id, created_at FROM push_tokens ORDER BY created_at DESC LIMIT 1")
    if not rows:
        print("NO_TOKENS")
        return
        
    token = rows[0]["token"]
    print(f"TOKEN: {token}")
    
    # 2. Send push
    res = send_expo_notifications(
        [token],
        "AIBrief24 E2E Test",
        "Testing delivery pipeline natively",
        data={"type": "test"}
    )
    print(f"TICKET: {json.dumps(res)}")
    
    # Extract ticket ID
    ticket_id = None
    try:
        data = res.get("responses", [])[0].get("data", [])[0]
        if data.get("status") == "ok":
            ticket_id = data.get("id")
    except:
        pass
        
    if not ticket_id:
        print("NO_TICKET_ID")
        return
        
    print(f"TICKET_ID: {ticket_id}")
    
    # Wait for receipt to be generated by Expo
    print("Waiting 6 seconds for FCM to return receipt to Expo...")
    time.sleep(6)
    
    # 3. Retrieve receipt
    receipt_res = requests.post(
        EXPO_RECEIPTS_URL,
        json={"ids": [ticket_id]},
        headers={"Accept": "application/json", "Content-Type": "application/json"}
    ).json()
    
    print(f"RECEIPT: {json.dumps(receipt_res)}")

if __name__ == "__main__":
    test_push()
